### ISSUE TITLE
Is it possible to share Go code?

### ISSUE THREAD

**Issue by sujit-baniya** [hkpeaks/peaks-consolidation#6]

**Comment by hkpeaks** [comment]
Old version Go code: https://github.com/hkpeaks/peaks-consolidation/tree/main/src

Current version Go code: https://github.com/hkpeaks/polars-cf-peaks/blob/main/cf-002%20InnerJoin-GroupBy/peakgo.go

I find difficulty to share Go code which support to build runtime. So I prefer to share more Python code.

App:
https://github.com/hkpeaks/polars-cf-peaks/blob/main/cf-002%20InnerJoin-GroupBy/peakrs.py

Streaming Library:
https://github.com/hkpeaks/polars-cf-peaks/blob/main/cf-002%20InnerJoin-GroupBy/peakpy.py

Query library written in Rust: peakrs.pyd. 

I plan early next year will allow users to install the Python-Rust version of Peaks by "pip install peakrs".

**Comment by sujit-baniya** [comment]
@hkpeaks Thanks for sharing the information.

https://github.com/hkpeaks/polars-cf-peaks/blob/main/cf-002%20InnerJoin-GroupBy/peakgo.go

I checked this and can't run as it is looking for `peakgo/peakgo`

**Comment by hkpeaks** [comment]
Please note that the application cannot operate as it currently lacks a DLL, which is an output that Go doesn’t provide for the Windows platform. However, I’m planning to make the Python-Rust version of Peaks available for installation via ‘pip install peakrs’ early next year. It’s important to mention that the project has transitioned to Python-Rust development because distributing a Go app isn’t feasible when a similar implementation can be achieved with the Python-Rust model. However I will keep concurrent development with csharp and go for internal research purpose.
